name: Building Project...

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running build!"
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: print message
        run: echo "Building Doubly-linked-list"
      - name: make doubleLinkedList
        run: make doubleLinkedList
      - name: make run
        run: make run
      - name: Running doubly-linked-list
        run: make runDoubleLinkedList
      - name: print message
        run: echo "Building Doubly-Linked_list Add at First"
      - name: make doubleAddatHead
        run: make doubleAddatHead
      - name: run runDoubleAtHead
        run: make runDoubleAtHead
      - name: run searchintoDoubleLinkedList
        run: make runsearchInList
      - name: run StackBuild
        run: make runstack
      - name: run Linear_Search
        run: make runLinearSearch
